# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: install Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
          xcode-version: 15

    - name: Build for testing
      run: xcodebuild build-for-testing -project CarCare.xcodeproj -scheme CarCare -destination 'platform=iOS Simulator,name=iPhone 15 Pro' 
